### ISSUE TITLE
Registering stereotaxic coordiates .csv to a more detailed atlas.  [Feature]

### ISSUE THREAD

**Issue by AngCamp** [brainglobe/brainreg-segment#132]
This may already be possible but to me it was unclear how to do this based on the tutorials https://brainglobe.info/documentation/brainreg-segment/index.html.  But i have a .csv of the 3d coordinates for every channel in a neuropixels probe.  I want to register them to a more detailed atlas than the annotations they provided and it is not clear to me how t do that using this tool, though it seems like it should be possible.

**Comment by adamltyson** [comment]
Hey @AngCamp, I don't think I know exactly what you mean. Could you explain what you're trying to achieve?

**Comment by AngCamp** [comment]
I am using neuropixels probe data which has already been collected and is now publicly available.  Each channel has been stored with metadata about it's position in the brain.  They have provided an anotation of which brain region each channel is located in, so CA1, VisCrtx etc etc.  I want to use a more detailed ABA mapping which could tell me which channels were located in the pyramidal layer of CA1.  As an example here is the meta data for some probes.  I restricted it to the CA1 channels but there are other channels in deeper brain structures as well as in cortex.  I want to get a more detailed annotation using another ABA mapping. 


https://drive.google.com/file/d/1qr7TkX3Tl_GLV9ZxVGeocp0TrBDm8wsI/view?usp=sharing

**Comment by AngCamp** [comment]
So I have an annotation for say `grey/CTX/CTXpl/Isocortex/VIS/VISp` and I want to go down to the level of `grey/CTX/CTXpl/Isocortex/VIS/VISp/VISp1`.  Using the x,y,z coordinates in the metadata.

**Comment by adamltyson** [comment]
brainreg-segment is designed for segmenting features in your own data. The best way of doing this is likely to use the [BrainGlobe Atlas API](https://brainglobe.info/documentation/bg-atlasapi/index.html) directly. If you load the points, then you should be able to do something like:
```python
COORD = (500, 300, 400)
from bg_atlasapi import BrainGlobeAtlas
atlas = BrainGlobeAtlas("allen_mouse_10um")
atlas.structure_from_coords(COORD, as_acronym=True)
```
The BrainGlobe version of the atlas may be in a different resolution and orientation to the one used to generate this data in the first place, so it may need to be re-scaled and reoriented.

**Comment by AngCamp** [comment]
Is there a way to make a figure depicting the probes path through the brain with the data I have?  Might be nice to make figures of that at some point.  From my reading your software is set up for people working with images they register to the ccf but it can't generate the path a probe took just using its coordinates.

**Comment by adamltyson** [comment]
The orientation may be different because all BrainGlobe atlases have the same coordinate system, that may vary from the version of the CCF you're using. The origin of the BG atlas will be the most superior, anterior, right voxel.

**Comment by AngCamp** [comment]
I will keep this in mind but I am seeing good correspondance between the new annotations and the old ones.  And from looking at my data I believe it has the same origin as the BG atlas.  There is no sudden change in region, the probes are being reannotated in a more detailed way as expected.
