### ISSUE TITLE
Windows: RuntimeError: Freetype library not found

### ISSUE THREAD

**Issue by horsto** [brainglobe/brainreg-segment#17]
Testing brainreg_segment under windows. 
The following error occurs when trying to start track tracing (clicking on the first point on the atlas):
```
WARNING: Traceback (most recent call last):
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\site-packages\freetype\raw.py", line 49, in <module>
    _lib = ctypes.CDLL(filename)
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\analysis\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by adamltyson** [comment]
Do you know if this happens on any other machines?

**Comment by horsto** [comment]
Never had this issue on my Mac. Will also try to start from a fresh conda env under windows (but doubt that’s the problem). Region segmentation seems to be fine.

**Comment by adamltyson** [comment]
Yep, sorry I meant on a different windows machine. A quick google suggests it could be a broken conda env/install.

**Comment by horsto** [comment]
Ok, I will check that more thoroughly, thanks! Will keep you updated.

**Comment by adamltyson** [comment]
[Looks like it might be a machine-specific thing.](https://forum.image.sc/t/error-freetype-library-not-found-during-adding-points/41742)

**Comment by adamltyson** [comment]
Closing this, as it's a system/napari issue rather than a brainreg issue.
