### ISSUE TITLE
Track tracing - spline points order

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainreg-segment#44]
Hi, 

I've been having problems with track tracing lately, it produces weird looking splines. It looks likes the spline is going through the control points in a weird order.
![image (2)](https://user-images.githubusercontent.com/17436313/131091176-c9eac96a-d8e6-4d50-bc5a-2bd2ac434137.png)
![image (1)](https://user-images.githubusercontent.com/17436313/131091184-cf86e344-4853-423e-a16a-d6a6277b39af.png)

I've been doing everything normally so I'm not sure what the problem is or how to fix it. Using fewer control points seems to help but still sometimes the spline is off.

**Comment by adamltyson** [comment]
This might be fixed now, but it's hard to test all cases. Could you install the release candidate (`pip install brainreg-segment==0.2.14rc0`) and see if the problem persists?

**Comment by adamltyson** [comment]
Fixed in `0.2.14`
