### ISSUE TITLE
Failing to install brainreg-segment from napari

### ISSUE THREAD

**Issue by gaiabianchini** [brainglobe/brainreg-segment#45]
Throught the napari software I am trying to install the brainreg-segment plugin, but after 1min of trying brainreg-segment just appears again in the list of available plugins and does not get installed. This does not happen with other plugins.

Any idea why that might be?

**Comment by adamltyson** [comment]
How did you install napari? Is it the bundled version, or did you install it via pip/conda? Also what operating system are you using?

**Comment by gaiabianchini** [comment]
I installed it via pip install in miniconda and I am using Windows.

**Comment by adamltyson** [comment]
Can you try installing the plugin directly from pip? `pip install brainreg-segment`

**Comment by gaiabianchini** [comment]
I did, but when opening napari it still does not come out in the list of installed plugins

**Comment by gaiabianchini** [comment]
I installed napari in the same enviroment as cellfinder and there was this issue. I now created a new enviroment just for napari and when launching napari from there I can download brainreg-segment. Solved!
